import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//  };
const sidebars = {
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'get-started',

    {
      type: 'category',
      label: '2. Foundations',
      link: { type: 'doc', id: 'foundations/index' },
      collapsible: true,
      collapsed: true,
      items: [
        'foundations/account-console',
        'foundations/workspace',
        'foundations/unity-catalog',
        'foundations/recap'
      ],
    },

    'cloud-tenants',

    {
      type: 'category',
      label: '4. Create workspaces',
      link: { type: 'doc', id: 'create-workspaces/index' },
      collapsible: true,
      collapsed: true,
      items: [
        'create-workspaces/azure',
        'create-workspaces/aws',
        'create-workspaces/gcp',
      ],
    },

    'post-deployment',
    'uc-governance-strategy',
    {
      type: 'category',
      label: '7. Access your data from Unity Catalog',
      link: { type: 'doc', id: 'access-your-data-from-uc/index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Cloud object storage',
          link: { type: 'doc', id: 'access-your-data-from-uc/cloud-object-storage/index' },
          items: [
            'access-your-data-from-uc/cloud-object-storage/azure',
            'access-your-data-from-uc/cloud-object-storage/aws'
          ],
        },

        'access-your-data-from-uc/external-systems/index'

      ],
    },
    'data-engineering',
    'data-warehouse',
    'aibi'

  ],
};

export default sidebars;

