import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//  };
const sidebars = {
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    // https://repo_url.com/databricks-journey/docs/motivation/
    'motivation',

    // https://repo_url.com/databricks-journey/docs/foundations/
    {
      type: 'category',

      label: 'Foundations',
      link: { type: 'doc', id: 'foundations/index' },
      collapsible: true,
      collapsed: false,
      items: [
        'foundations/architecture',
        'foundations/workspace',
        'foundations/unity-catalog',
        'foundations/account-console',
        'foundations/recap'
      ],
    },

    // https://repo_url.com/databricks-journey/docs/before-you-start/
    'before-you-start',

    // https://repo_url.com/databricks-journey/docs/create-workspaces/
    {
      type: 'category',

      label: 'Create Workspaces',
      link: { type: 'doc', id: 'create-workspaces/index' },
      collapsible: true,
      collapsed: false,
      items: [
        'create-workspaces/azure',
        'create-workspaces/aws',
      ],
    },

    // https://repo_url.com/databricks-journey/docs/post-deployment/
    {
      type: 'category',

      label: 'Post-deployment Setup',
      link: { type: 'doc', id: 'post-deployment/index' },
      collapsible: true,
      collapsed: false,
      items: [
        'post-deployment/account'
      ],
    },

    // https://repo_url.com/databricks-journey/docs/access-the-data/
    {
      type: 'category',

      label: 'Access the Data',
      link: { type: 'doc', id: 'access-the-data/index' },
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Access through UC',
          link: { type: 'doc', id: 'access-the-data/uc-objects/index' },
          items: [
            'access-the-data/uc-objects/azure',
            'access-the-data/uc-objects/aws'
          ],
        }
      ],
    }

  ],
};

export default sidebars;

