import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//  };
const sidebars = {
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    // https://repo_url.com/databricks-journey/docs/motivation/
    'motivation',

    // https://repo_url.com/databricks-journey/docs/foundations/
    {
      type: 'category',
      label: '2. Foundations',
      link: { type: 'doc', id: 'foundations/index' },
      collapsible: true,
      collapsed: false,
      items: [
        'foundations/architecture',
        'foundations/workspace',
        'foundations/unity-catalog',
        'foundations/account-console',
        'foundations/recap'
      ],
    },

    // https://repo_url.com/databricks-journey/docs/before-you-start/
    'before-you-start',

    // https://repo_url.com/databricks-journey/docs/create-workspaces/
    {
      type: 'category',
      label: '4. Create workspaces',
      link: { type: 'doc', id: 'create-workspaces/index' },
      collapsible: true,
      collapsed: false,
      items: [
        'create-workspaces/azure',
        'create-workspaces/aws',
        'create-workspaces/gcp',
      ],
    },

    // https://repo_url.com/databricks-journey/docs/post-deployment/
    {
      type: 'category',
      label: '5. Post-deployment Setup',
      link: { type: 'doc', id: 'post-deployment/index' },
      collapsible: true,
      collapsed: false,
      items: [
        'post-deployment/account'
      ],
    },

    'uc-governance-strategy',

    // https://repo_url.com/databricks-journey/docs/access-your-data-from-uc/
    {
      type: 'category',
      label: '7. Access your data from Unity Catalog',
      link: { type: 'doc', id: 'access-your-data-from-uc/index' },
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Cloud object storage',
          link: { type: 'doc', id: 'access-your-data-from-uc/cloud-object-storage/index' },
          items: [
            'access-your-data-from-uc/cloud-object-storage/azure/azure',
            'access-your-data-from-uc/cloud-object-storage/aws/aws'
          ],
        },
        {
          type: 'category',
          label: 'External systems and databases',
          link: { type: 'doc', id: 'access-your-data-from-uc/external-systems/index' },
          items: [
            'access-your-data-from-uc/external-systems/azure/azure',
            'access-your-data-from-uc/external-systems/aws/aws'
          ],
        }

      ],
    }

  ],
};

export default sidebars;

